package com.mycompany.bibliotecafinal;
public enum EnumGeneros{
    COMEDIA, DRAMA, FANTASIA, THRILLER, TERROR, ROMANCE, POLICIAL, DISTOPIA, ACAO, AVENTURA, BIBLIOGRAFIA, AUTOAJUDA, TRUECRIME, DIDATICO; 
}